# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  # This replaces your manual 'uv venv' and 'pip install' steps
  setup:backend:
    desc: "Create venv and sync dependencies"
    dir: backend
    cmds:
      - uv sync
    sources:
      - pyproject.toml
      - uv.lock
    generates:
      - .venv/pyvenv.cfg # Tells Task the venv is now "ready"

  run:backend:
    desc: "Start FastAPI"
    deps: [setup:backend]
    dir: backend
    cmds:
      - uv run uvicorn main:app --reload

  # Frontend tasks
  setup:frontend:
    desc: "Install frontend dependencies"
    dir: frontend
    cmds:
      - npm install
    sources:
      - package.json
      - package-lock.json
    generates:
      - node_modules/.package-lock.json

  run:frontend:
    desc: "Start frontend development server"
    deps: [setup:frontend]
    dir: frontend
    cmds:
      - npm run dev

  # Run both backend and frontend in parallel
  run:dev:
    desc: "Start both backend and frontend in parallel"
    deps: [setup:backend, setup:frontend]
    cmds:
      - task --parallel run:backend run:frontend

  # Sync frontend from quant-crew-ui to quant-crew/frontend
  sync:frontend:
    desc: "Sync frontend from ~/workspace/quant-crew-ui to frontend/"
    cmds:
      - rsync -av --delete --exclude 'node_modules' --exclude '.next' --exclude '.git' --exclude 'dist' --exclude 'build' ~/workspace/quant-crew-ui/ frontend/
      - echo "✓ Frontend synced from ~/workspace/quant-crew-ui to frontend/"
